### ISSUE TITLE
Add update support for windows

### ISSUE THREAD

**Issue by sarthakchaudhary13** [sarthakchaudhary13/sapera#8]
Right now, when while running `sapera update` on windows we are getting an error as bash is not it's default shell.
**Steps to solve this**
- Create a seperate update.cmd file for updating (see updater.sh)
- Modify sapera/main/main.py to check for os and run the right script

**Comment by Nagendracse1** [comment]
Can I take it?

**Comment by sarthakchaudhary13** [comment]
Yeah sure, go ahead if you need any help feel free to ask.

**Comment by sarthakchaudhary13** [comment]
Given the silence, I am assuming you are not working on this, I've gone ahead and fixed the issue with PR #10
